<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xml.netbeans.org/schema/ProyectoSCHEMA" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPELProyecto/src/GestionaProyectoWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="GestionaProyectoWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/BPELProyecto/src/GestionaProyectoWSDL">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BPELProyecto/src/GestionaProyectoWSDL">
            <xsd:import namespace="http://xml.netbeans.org/schema/ProyectoSCHEMA" schemaLocation="ProyectoSCHEMA.xsd"/>
        </xsd:schema>
    </types>
    <message name="GestionaProyectoWSDLOperationRequest">
        <part element="ns:eltoGestionaPedido" name="datos_pedido"/>
    </message>
    <message name="GestionaProyectoWSDLOperationResponse">
        <part element="ns:eltoRespuestaGestiona" name="respuesta_pedido"/>
    </message>
    <message name="GestionaProyectoWSDLOperationFault">
        <part element="ns:eltoExcepcionGenerica" name="excepcion_pedido"/>
    </message>
    <portType name="GestionaProyectoWSDLPortType">
        <operation name="GestionaProyectoWSDLOperation">
            <input message="tns:GestionaProyectoWSDLOperationRequest" name="input1"/>
            <output message="tns:GestionaProyectoWSDLOperationResponse" name="output1"/>
            <fault message="tns:GestionaProyectoWSDLOperationFault" name="fault1"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="GestionaProyectoWSDL">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="GestionaProyectoWSDLPortTypeRole" portType="tns:GestionaProyectoWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
