<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSCreditoWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSCreditoWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSCreditoWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wscredito/">
    <import location="http://localhost:8080/WS_Credito_Libros2/WSCredito?WSDL" namespace="http://wscredito/"/>
    <plnk:partnerLinkType name="WS_CreditoLinkType">
        <plnk:role name="WS_CreditoRole" portType="ns:WS_Credito"/>
    </plnk:partnerLinkType>
</definitions>
